# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-19 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
