# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('no_shore', models.BooleanField(default=False, verbose_name='No Shore')),
                ('no_paid', models.BooleanField(default=False, verbose_name='ติดจ่ายตังค์')),
                ('no_customs', models.BooleanField(default=False, verbose_name='ติด Custom')),
                ('no_vgm', models.BooleanField(default=False, verbose_name='No VGM')),
                ('late_gate', models.BooleanField(default=False, verbose_name='Late Gate')),
                ('other', models.CharField(blank=True, max_length=100, null=True, verbose_name='อื่นๆ')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
