# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
