# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
