# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateout', '0002_auto_20180327_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
