# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateout', '0003_container_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
