# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import gateout.models


class Migration(migrations.Migration):

    dependencies = [
        ('gateout', '0004_auto_20180328_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container_images',
            name='image',
            field=models.ImageField(upload_to=gateout.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='container_images',
            name='thumbnails_image',
            field=models.ImageField(upload_to=gateout.models.thumbnails_directory_path),
        ),
    ]
